#!/bin/bash

# open textwrangler and open a file

FILE=$1

if [[ -z "$FILE" ]]
then
	open -a /Applications/TextWrangler.app/ 
else
	if [ -f "$FILE" ]
	then
    	open -a /Applications/TextWrangler.app/ "$FILE"
	else
    	edit "$FILE"
	fi
fi
